In [35]:
import pandas as pd

In [36]:
def fak_dat_gen(n):
    from faker import Faker
# Create a Faker instance
    fake = Faker()

# Initialize lists to store the data
    names = []
    emails = []
    ssns = []
    phone_numbers = []
    dates_of_birth = []
    incomes = []

# Generate 1000 rows of data
    for _ in range(n):
        name = fake.name()
        email = fake.email()
        ssn = fake.ssn()
        phone_number = fake.phone_number()
        date_of_birth = fake.date_of_birth(minimum_age=18, maximum_age=65)
        income = fake.pydecimal(left_digits=5, right_digits=2, positive=True)

        names.append(name)
        emails.append(email)
        ssns.append(ssn)
        phone_numbers.append(phone_number)
        dates_of_birth.append(date_of_birth)
        incomes.append(income)

# Create a DataFrame from the lists
    data = pd.DataFrame({
        'Name': names,
        'Email': emails,
        'SSN': ssns,
        'Phone Number': phone_numbers,
        'Date of Birth': dates_of_birth,
        'Income': incomes
    })
    return data

In [37]:
df=fak_dat_gen(10000)

In [38]:
df.shape

(10000, 6)

Code for Anonymizer

In [97]:
input_df=pd.read_csv('fake_data.csv')

In [41]:
dat_info=pd.DataFrame({
    'column_name':input_df.columns.to_list(),
    'data_type':input_df.dtypes.to_list(),
    'null_count':input_df.isnull().sum().to_list(),
    'unique_count':input_df.nunique().to_list(),
    'total_count':[len(input_df[x]) for x in input_df.columns]
})

In [98]:
dat_info.head()

    column_name data_type  null_count  unique_count  total_count
0    Unnamed: 0     int64           0          1000         1000
1          Name    object           0           989         1000
2         Email    object           0           996         1000
3           SSN    object           0          1000         1000
4  Phone Number    object           0          1000         1000

Masking started for Email .......
Masking completed for Email for  1000  emails

,Unnamed: 0,Name,SSN,Phone Number,Date of Birth,Income,Email
0,0,Juan Bowen,119-11-4145,(676)793-6070,1993-03-19,40170.38,owatson@example.net
1,1,Melissa Hall,123-03-3851,001-359-441-6724x128,2003-07-05,41175.47,icampos@example.net
2,2,Maria Baldwin,518-01-5032,537.643.1238x09772,1960-09-16,24304.28,lopezshirley@example.com
3,3,Connie Murray,609-50-1959,393-223-2852x2015,1999-04-28,94270.18,palmertom@example.org
4,4,Kaitlin Berg,102-91-5689,001-413-308-7153,1960-01-27,45188.14,kennethsmith@example.net
...,...,...,...,...,...,...,...
995,995,Scott Rich,204-70-8980,798-744-6756x59477,1994-01-05,72402.40,william42@example.org
996,996,Kelly Palmer,251-76-9431,272.513.5420x2263,1988-04-19,23781.98,carrollkenneth@example.net
997,997,Jennifer Cardenas,083-02-6575,+1-838-450-7355x239,2000-05-16,32959.24,holderleslie@example.com
998,998,Larry Gross,616-88-2361,219-558-9613,1985-06-22,95375.81,sallynovak@example.com
999,999,Brian Chapman,845-88-7494,+1-586-733-7070x679,1976-03-30,83164.54,tcordova@example.net

In [121]:
def F_danon_email(df,id,pii_col):
    lst=[id,pii_col]
    df1=df[lst]
    print('Masking started for',pii_col,'.......')
    # Remove duplicates in-place
    df2=df1.drop_duplicates(subset=lst)
    df2.drop(pii_col,axis=1,inplace=True)

    email_lst_fk=[]
    for x in range(len(df2)):
        email=fake.unique.email()
        email_lst_fk.append(email)
    df2[pii_col]=email_lst_fk
    #Merging with Original data
    input_data=df.drop(columns=[pii_col])
    out_data=input_data.merge(df2,how='left',on=id)
    print('Masking completed for',pii_col,'for ',len(email_lst_fk),' emails')
    #To maintain same order of column as input var
    lt=df.columns.to_list()
    out_data=out_data[lt]
    # F_danon_email(input_df,id='Unnamed: 0',pii_col='Email')
    return out_data

In [130]:
def F_danon_fname(df,id,pii_col):
    lst=[id,pii_col]
    df1=df[lst]
    print('Masking started for',pii_col,'.......')
    # Remove duplicates in-place
    df2=df1.drop_duplicates(subset=lst)
    df2.drop(pii_col,axis=1,inplace=True)

    lst_fk=[]
    for x in range(len(df2)):
        mask_data=fake.first_name()
        lst_fk.append(mask_data)
    df2[pii_col]=lst_fk
    #Merging with Original data
    input_data=df.drop(columns=[pii_col])
    out_data=input_data.merge(df2,how='left',on=id)
    print('Masking completed for',pii_col,'for ',len(lst_fk),' names')
    #To maintain same order of column as input var
    lt=df.columns.to_list()
    out_data=out_data[lt]
    # F_danon_fname(input_df,id='Unnamed: 0',pii_col='Name')
    return out_data

In [137]:
def F_danon_phn(df,id,pii_col):
    lst=[id,pii_col]
    df1=df[lst]
    print('Masking started for',pii_col,'.......')
    # Remove duplicates in-place
    df2=df1.drop_duplicates(subset=lst)
    df2.drop(pii_col,axis=1,inplace=True)

    lst_fk=[]
    for x in range(len(df2)):
        mask_data=fake.phone_number()
        lst_fk.append(mask_data)
    df2[pii_col]=lst_fk
    #Merging with Original data
    input_data=df.drop(columns=[pii_col])
    out_data=input_data.merge(df2,how='left',on=id)
    print('Masking completed for',pii_col,'for ',len(lst_fk),' phones')
    #To maintain same order of column as input var
    lt=df.columns.to_list()
    out_data=out_data[lt]
    # F_danon_phn(input_df,id='Unnamed: 0',pii_col='Phone Number')
    return out_data

In [155]:
def F_danon_ssn(df,id,pii_col):
    lst=[id,pii_col]
    df1=df[lst]
    print('Masking started for',pii_col,'.......')
    # Remove duplicates in-place
    df2=df1.drop_duplicates(subset=lst)
    df2.drop(pii_col,axis=1,inplace=True)

    lst_fk=[]
    for x in range(len(df2)):
        mask_data=fake.ssn()
        lst_fk.append(mask_data)
    df2[pii_col]=lst_fk
    #Merging with Original data
    input_data=df.drop(columns=[pii_col])
    out_data=input_data.merge(df2,how='left',on=id)
    print('Masking completed for',pii_col,'for ',len(lst_fk),' SSN')
    lt=df.columns.to_list()
    out_data=out_data[lt]
    # F_danon_ssn(input_df,id='Unnamed: 0',pii_col='SSN')
    return out_data

In [156]:
input_df

,Unnamed: 0,Name,Email,SSN,Phone Number,Date of Birth,Income
0,0,Juan Bowen,juliawhitaker@example.net,119-11-4145,(676)793-6070,1993-03-19,40170.38
1,1,Melissa Hall,markmcfarland@example.com,123-03-3851,001-359-441-6724x128,2003-07-05,41175.47
2,2,Maria Baldwin,shawnevans@example.org,518-01-5032,537.643.1238x09772,1960-09-16,24304.28
3,3,Connie Murray,phillip13@example.com,609-50-1959,393-223-2852x2015,1999-04-28,94270.18
4,4,Kaitlin Berg,sabrina16@example.net,102-91-5689,001-413-308-7153,1960-01-27,45188.14
...,...,...,...,...,...,...,...
995,995,Scott Rich,mary52@example.net,204-70-8980,798-744-6756x59477,1994-01-05,72402.40
996,996,Kelly Palmer,tommyhaynes@example.org,251-76-9431,272.513.5420x2263,1988-04-19,23781.98
997,997,Jennifer Cardenas,justinhall@example.net,083-02-6575,+1-838-450-7355x239,2000-05-16,32959.24
998,998,Larry Gross,todd84@example.com,616-88-2361,219-558-9613,1985-06-22,95375.81
999,999,Brian Chapman,zhangjerry@example.net,845-88-7494,+1-586-733-7070x679,1976-03-30,83164.54

In [157]:
x=F_danon_ssn(input_df,id='Unnamed: 0',pii_col='SSN')

Masking started for SSN .......
Masking completed for SSN for  1000  SSN

In [158]:
input_df.head()

,Unnamed: 0,Name,Email,SSN,Phone Number,Date of Birth,Income
0,0,Juan Bowen,juliawhitaker@example.net,119-11-4145,(676)793-6070,1993-03-19,40170.38
1,1,Melissa Hall,markmcfarland@example.com,123-03-3851,001-359-441-6724x128,2003-07-05,41175.47
2,2,Maria Baldwin,shawnevans@example.org,518-01-5032,537.643.1238x09772,1960-09-16,24304.28
3,3,Connie Murray,phillip13@example.com,609-50-1959,393-223-2852x2015,1999-04-28,94270.18
4,4,Kaitlin Berg,sabrina16@example.net,102-91-5689,001-413-308-7153,1960-01-27,45188.14

In [159]:
x.head()

,Unnamed: 0,Name,Email,SSN,Phone Number,Date of Birth,Income
0,0,Juan Bowen,juliawhitaker@example.net,410-55-9472,(676)793-6070,1993-03-19,40170.38
1,1,Melissa Hall,markmcfarland@example.com,468-56-7877,001-359-441-6724x128,2003-07-05,41175.47
2,2,Maria Baldwin,shawnevans@example.org,215-89-7509,537.643.1238x09772,1960-09-16,24304.28
3,3,Connie Murray,phillip13@example.com,567-67-2560,393-223-2852x2015,1999-04-28,94270.18
4,4,Kaitlin Berg,sabrina16@example.net,532-10-1292,001-413-308-7153,1960-01-27,45188.14

In [110]:
id='Unnamed: 0'
pii_col='Email'
lst=[id,pii_col]
df1=input_df[lst]
# Remove duplicates in-place
df2=df1.drop_duplicates(subset=lst)
df2.drop(pii_col,axis=1,inplace=True)
email_lst_fk=[]
for x in range(len(df2)):
    email=fake.unique.email()
    print(email)
    email_lst_fk.append(email)
df2[pii_col]=email_lst_fk

#Merging with Original data
input_data=input_df.drop(columns=[pii_col])
out_data=input_data.merge(df2,how='left',on=id)

jessica84@example.net
brittanysummers@example.net
cford@example.net
lunalisa@example.net
hannagabrielle@example.org
lmcmahon@example.net
prodriguez@example.net
oliviamartin@example.com
lpatterson@example.com
atkinsonconnie@example.net
ablake@example.net
kevinstephens@example.net
jennifer23@example.org
gabriellegonzales@example.net
bauernorman@example.org
duncanmandy@example.com
anthony78@example.com
christophergonzales@example.org
valentinecrystal@example.com
annatapia@example.net
qsmith@example.org
riosheather@example.net
natashacook@example.com
hharrington@example.net
hernandezjeanette@example.net
daniel60@example.com
josephjordan@example.org
sandersnicholas@example.com
michael72@example.org
tamara25@example.com
nclarke@example.net
dawncollins@example.com
jlewis@example.net
steven47@example.net
nelsonkevin@example.com
agibbs@example.com
samanthagray@example.org
serranojames@example.org
vcarter@example.com
usmith@example.com
jenniferscott@example.com
reynoldsmichael@example.org
crystalzuniga@example.net
robinsonderek@example.net
jeffrey26@example.com
charles74@example.com
sergio67@example.com
samuel16@example.com
randall80@example.com
timothymorgan@example.org
tiffany01@example.com
sarahsmall@example.net
cynthiavaldez@example.org
timothyrobinson@example.com
markfernandez@example.com
kramos@example.com
martinezdakota@example.org
kimberlycox@example.org
larrymurphy@example.org
xelliott@example.com
joseph69@example.net
johndavis@example.net
monicaglenn@example.com
virginia18@example.org
austintanner@example.com
bartlettjoseph@example.net
emily37@example.org
parkerbrian@example.com
david10@example.net
ortegaheidi@example.org
kellymontoya@example.com
sandraburton@example.org
msweeney@example.net
jacob92@example.com
james01@example.org
sking@example.net
suarezshannon@example.com
brent03@example.org
dawsonjeffrey@example.org
connieyoung@example.org
joshua02@example.com
harringtonkenneth@example.org
smithsara@example.net
martinezalejandro@example.org
tjacobs@example.com
derickson@example.com
larsondavid@example.org
calebblack@example.net
millerarthur@example.org
bryanheather@example.org
ohunter@example.com
cartermark@example.net
christinecarter@example.org
david81@example.net
maria25@example.com
mary26@example.com
linda69@example.com
nmack@example.com
manninglauren@example.org
kimberly23@example.com
cmontgomery@example.com
julia77@example.org
jeffrey92@example.com
ruizscott@example.net
amy02@example.org
yhicks@example.com
campbellmark@example.com
mmartinez@example.com
morganmike@example.com
elizabeth10@example.org
richard80@example.net
obrown@example.org
stevemorris@example.org
jamesbradley@example.com
pstuart@example.com
joshuajohnson@example.org
christy13@example.org
george63@example.org
bradley41@example.net
craigreyes@example.org
zserrano@example.com
gibsonchristina@example.com
kramerbrenda@example.org
hubbardjacqueline@example.org
qcarrillo@example.org
rivaspamela@example.com
donna18@example.net
brian46@example.com
sarah19@example.net
tschmitt@example.com
sandrajackson@example.net
jody71@example.com
ywilliams@example.com
jspears@example.com
kevin45@example.net
serranochristine@example.org
boydlindsey@example.com
katherinemiller@example.net
michaelrivera@example.net
jessica61@example.net
christopher06@example.net
rossmark@example.net
aaron85@example.org
michael69@example.com
katherineserrano@example.com
michael46@example.org
anthonyrivers@example.org
lindareilly@example.net
angela52@example.com
michael95@example.net
craigmckee@example.com
logan03@example.net
erincompton@example.net
tmcbride@example.com
gsmith@example.org
alyssa67@example.com
zacharywilson@example.org
olittle@example.net
hoovermolly@example.net
haley77@example.org
gjohnson@example.org
rodriguezbeth@example.net
palmerkaren@example.org
jonesfrancisco@example.org
kathrynsloan@example.com
gharrison@example.net
schmidtmeredith@example.net
crystal43@example.org
ycooper@example.org
alex27@example.com
carrillotodd@example.com
thomas78@example.net
walkerdiana@example.com
monique37@example.com
john11@example.org
smacdonald@example.org
swilson@example.com
arnoldtrevor@example.net
akim@example.net
gabrieldeleon@example.net
jonesdanielle@example.com
scottvanessa@example.org
katelyn77@example.net
codyhale@example.com
cliffordfinley@example.com
micheleadams@example.net
thomas40@example.net
monica78@example.org
dgibson@example.org
grayrandy@example.org
tatejenna@example.net
cassandraalexander@example.net
nelsonreginald@example.org
andre97@example.com
christopherwang@example.org
morgan82@example.org
cookmarcus@example.net
doylepaul@example.com
wrightsamantha@example.net
pguerra@example.org
cblair@example.com
gmurray@example.com
welchpamela@example.org
hwilson@example.org
lwhite@example.com
eric08@example.org
howardbeverly@example.org
cindyguzman@example.net
wardtimothy@example.org
mhanson@example.org
raymondanne@example.net
daltonwilson@example.com
sally82@example.com
lisa41@example.net
willie18@example.org
kochbarbara@example.org
omar32@example.net
usolis@example.com
shannon37@example.net
dalejackson@example.org
ogriffin@example.org
autumnfleming@example.org
cheyenne25@example.com
mitchellhernandez@example.com
traci16@example.com
shepherdderrick@example.net
qwilson@example.net
tinaallen@example.org
klewis@example.com
haroldanderson@example.net
isabellagraves@example.com
lorraine41@example.com
sharonflynn@example.net
skinnercurtis@example.com
elizabeth53@example.net
sheltonjames@example.org
samuelcarter@example.com
tuckerscott@example.org
patriciasmith@example.org
housemichelle@example.com
mezaryan@example.com
smartin@example.com
brandon80@example.com
samanthaparsons@example.com
danastrickland@example.net
shane02@example.net
melinda05@example.org
michael39@example.net
hschaefer@example.net
vsteele@example.com
jeremiah52@example.net
ramoskatherine@example.com
smithchristopher@example.com
ljohnson@example.net
daniel07@example.org
amanda35@example.org
saguilar@example.com
rrogers@example.com
christopher49@example.com
edwardscrystal@example.org
jared46@example.org
apratt@example.org
richard50@example.com
dustingibson@example.org
briansoto@example.org
williamdiaz@example.org
santoskyle@example.org
cenglish@example.org
chill@example.com
banksrandy@example.com
kli@example.com
davidjordan@example.org
bowmanhannah@example.org
joseph71@example.org
morganjoseph@example.net
betty76@example.org
ianwilliams@example.org
snydersherry@example.net
zlee@example.com
wknight@example.org
erin63@example.com
jeffreygriffin@example.net
pricethomas@example.org
johnsonrobert@example.com
edwarddavis@example.com
lucasjonathan@example.com
pattersondiana@example.net
imiller@example.org
timothyfletcher@example.net
paul36@example.net
jessicabaker@example.net
ronniemaddox@example.com
jonathanbolton@example.com
bbecker@example.net
angela38@example.com
clarkrobert@example.com
mitchellbush@example.com
richardsonjennifer@example.org
jason44@example.com
stephaniebuck@example.org
gblackwell@example.net
andersongina@example.com
christiankathleen@example.org
tlynch@example.com
dwayne71@example.net
donaldhunter@example.net
walkergeorge@example.org
vincent06@example.org
sarahcampos@example.org
kingjessica@example.org
mcdanielnicole@example.net
gutierrezvalerie@example.org
briannamendoza@example.net
wilsonkim@example.com
tiffanymata@example.net
juliemcgrath@example.com
lauracarter@example.net
victoria35@example.net
matthewaustin@example.net
andrewmedina@example.net
james29@example.net
zacharycooper@example.com
masseynicholas@example.org
ubrown@example.net
matthewthornton@example.org
justinwilson@example.com
justin70@example.org
kelly12@example.net
beckdaniel@example.org
michael25@example.org
angelicasanford@example.com
miguel40@example.net
hunterpadilla@example.net
thomas65@example.net
tjones@example.net
robertsmatthew@example.com
westrebecca@example.net
alvaradosteven@example.com
william75@example.org
richard91@example.org
alexandria48@example.org
karendavidson@example.net
soliswilliam@example.net
lindsey69@example.net
wesley40@example.net
jmoore@example.com
michael95@example.com
kevingomez@example.org
bradleyjonathan@example.net
scottking@example.net
brettmays@example.com
oneilldanielle@example.org
klinescott@example.com
gclark@example.org
marialin@example.org
lwalsh@example.org
ule@example.net
wdavidson@example.net
csanders@example.org
james51@example.net
mgomez@example.org
angelaberry@example.net
mitchell10@example.com
donalddavis@example.com
whitebrad@example.org
kaitlinkrueger@example.net
jessicaandrews@example.org
bcordova@example.net
mstone@example.com
williamscarl@example.org
zmartinez@example.net
andrew75@example.org
joan50@example.net
stevenlawrence@example.org
catherine45@example.net
brownpatricia@example.net
veronicawolfe@example.org
joseph19@example.net
qcastillo@example.com
lopezmiranda@example.com
joneselizabeth@example.com
nicholas63@example.org
scottlisa@example.org
danny55@example.org
willierussell@example.org
lori03@example.com
millerjoseph@example.com
paige81@example.net
marie07@example.net
kristin41@example.org
gary39@example.net
edwardthomas@example.com
gomezjames@example.com
cheryl66@example.net
maurice62@example.com
francokeith@example.org
joshua45@example.org
timothy86@example.net
vbrennan@example.net
tinacastro@example.org
brooke27@example.com
weaverjustin@example.net
pmorales@example.com
garrettknapp@example.org
julie44@example.org
nathanielswanson@example.net
rgates@example.org
lewiserin@example.org
williamholland@example.com
stevenkim@example.net
krista79@example.org
simmonsjodi@example.com
erikagarcia@example.net
irichardson@example.net
timothybrown@example.com
zowens@example.com
umoore@example.com
samuelwhite@example.org
sampsongerald@example.net
ashley29@example.org
ftorres@example.net
chutchinson@example.com
kimayers@example.com
smithkathy@example.com
rhondawhite@example.com
lisagutierrez@example.net
katelyn69@example.net
gharvey@example.com
tarapeterson@example.com
bdavis@example.com
beckanthony@example.net
angela27@example.net
bsanchez@example.com
randy94@example.org
stephensjeremy@example.net
rgardner@example.org
obrienelizabeth@example.net
johnsonbilly@example.net
jonesstacy@example.net
stephanie98@example.com
jcamacho@example.com
joshua12@example.net
ruizfrancisco@example.org
blopez@example.com
zscott@example.org
megan30@example.com
melissaturner@example.org
ibarrachristopher@example.net
silvadonald@example.net
murraychris@example.org
kaitlynswanson@example.com
cummingspeter@example.org
knoxdaniel@example.net
ramirezmathew@example.org
chelsea03@example.com
qbautista@example.net
joannamurray@example.org
rebeccamyers@example.com
jason59@example.com
amandahubbard@example.net
adrian57@example.com
cynthia65@example.org
zimmermanlisa@example.org
sjohnson@example.com
urivera@example.net
joseorozco@example.net
hlam@example.net
sean08@example.org
martinezdenise@example.com
anna60@example.net
hornmarissa@example.org
nchandler@example.com
kathryn12@example.net
heather68@example.net
qharrison@example.com
lcampos@example.com
chrisallen@example.org
fowens@example.net
diazgregory@example.org
martinezhannah@example.com
cathy55@example.net
allen56@example.org
lyonssamuel@example.net
bryanortega@example.net
jillrichardson@example.net
ricepatricia@example.net
frazierderek@example.com
cochranelizabeth@example.com
nancywilliams@example.net
meyerwendy@example.net
imercer@example.org
ybailey@example.net
qpugh@example.com
christianmoore@example.org
alexdominguez@example.net
hooverdana@example.org
yavila@example.org
valentinerussell@example.com
shawn69@example.net
joyce98@example.net
john16@example.com
greencarol@example.net
hermannicole@example.org
mark46@example.com
justin83@example.net
zhall@example.com
manuelwu@example.org
xjackson@example.net
youngmonica@example.org
fthompson@example.org
abigail94@example.org
bradleyrivers@example.net
michael94@example.com
ataylor@example.net
laura36@example.org
edwardwright@example.org
kwalker@example.com
catherinedunlap@example.net
williamstheresa@example.org
mariahpeterson@example.org
rwilson@example.com
swansonmegan@example.com
steelenicole@example.com
gordonsarah@example.com
ncooke@example.org
deleonandrew@example.org
julie71@example.net
andersonjerry@example.com
perrymark@example.org
bclark@example.com
donnathomas@example.com
mariosanchez@example.org
annanewman@example.com
sosborne@example.org
cbrown@example.org
sarah92@example.net
holmesjane@example.net
leekimberly@example.com
slee@example.com
lgomez@example.net
ofox@example.com
bryantdaniel@example.com
gmorrow@example.org
morenoangela@example.org
melindamiller@example.net
bsmith@example.net
shawn34@example.com
vkennedy@example.com
eatonchris@example.net
joshua35@example.net
jessica78@example.net
charlesallen@example.org
hulllinda@example.com
nicole48@example.org
schmittkristen@example.org
brewertammy@example.net
jsullivan@example.net
ashleyedwards@example.net
clementsjoseph@example.net
john69@example.com
kristy61@example.net
simpsonmichael@example.net
david42@example.com
julie71@example.com
rlewis@example.com
jonathanfisher@example.org
smithaaron@example.com
bakerpatrick@example.com
warrenstacy@example.org
eric81@example.org
rachelcarter@example.com
moyerzachary@example.org
fergusontiffany@example.org
lisa13@example.org
hmitchell@example.org
phillipsjason@example.net
tmalone@example.com
joshua32@example.net
rachel11@example.org
julie59@example.com
mariaclayton@example.net
nicole60@example.org
joelbailey@example.org
davidwilliams@example.org
misty95@example.net
dpratt@example.org
elizabeth29@example.org
howardkimberly@example.com
owilliams@example.net
victoriawise@example.org
lhendricks@example.org
walkergrace@example.org
juareztony@example.org
shannon06@example.org
yyates@example.com
hubbarddavid@example.com
lauren69@example.net
courtney76@example.org
jesseross@example.com
enichols@example.com
thomasbailey@example.net
aaronpotter@example.org
nathan45@example.net
gcox@example.net
timothysalazar@example.org
arielbuck@example.org
michelle76@example.net
williamskatherine@example.org
shepherdrobin@example.net
sharonbuchanan@example.org
maxwellpamela@example.net
mcdonaldjoshua@example.com
michael16@example.org
coxsamantha@example.net
castillojeremiah@example.org
jonesrhonda@example.net
nicholasramsey@example.org
ryanmoore@example.com
charlesoliver@example.com
hermanjacqueline@example.net
dennisamy@example.org
daniel74@example.org
kgilmore@example.org
chenarthur@example.net
dfrazier@example.org
ykim@example.org
owilliams@example.org
brittney46@example.net
rduncan@example.net
madisonhernandez@example.com
timothywillis@example.org
natalielee@example.net
lukemartinez@example.net
tracy76@example.net
kevincampbell@example.org
sampsonmarie@example.net
tammienichols@example.org
rmcbride@example.net
nbrown@example.com
tony20@example.net
karenbenitez@example.org
vstephens@example.org
tanderson@example.net
along@example.net
garnererin@example.net
eprice@example.org
danielgarcia@example.com
markhall@example.com
proach@example.com
marissamills@example.net
stevensmith@example.com
coxmarcus@example.org
james17@example.com
diane87@example.net
shannonbrewer@example.com
michaelsanchez@example.com
adamperry@example.org
ryanshepherd@example.net
ostevens@example.net
warnerlaura@example.net
julia62@example.com
jacksonbarry@example.net
runderwood@example.com
preyes@example.net
jenna42@example.com
joshua85@example.org
ldavidson@example.com
ssnow@example.net
nicoleguerrero@example.org
danielwilliams@example.net
mcampos@example.net
thomasmeredith@example.com
njohns@example.net
florescasey@example.org
lrodriguez@example.com
laura04@example.net
adrianjenkins@example.com
samantha79@example.com
johnsonjade@example.com
moonanthony@example.com
ugordon@example.com
qforbes@example.net
moralesandrew@example.org
roberto23@example.org
chaveztimothy@example.net
walshmark@example.net
cindy11@example.com
ufrank@example.com
francis00@example.com
blarsen@example.org
robert01@example.net
dawnhenderson@example.com
jaywells@example.org
narroyo@example.com
kimberly93@example.org
hernandezjason@example.org
jasmin44@example.org
icook@example.net
johnny30@example.net
andrew17@example.net
nicholas21@example.com
huntersarah@example.net
palmercynthia@example.com
tarahutchinson@example.net
gleach@example.org
ohernandez@example.com
deborahclarke@example.net
chernandez@example.org
penamelissa@example.com
yrice@example.net
blankenshiptodd@example.com
wcox@example.org
warrenjanice@example.net
hendrixapril@example.net
watersbrian@example.net
ewhitehead@example.com
estesdavid@example.net
ilevine@example.com
jacksoncraig@example.org
jason74@example.net
sbrown@example.org
josepharnold@example.org
andrew19@example.com
vbrown@example.org
troy64@example.com
eric34@example.com
bdougherty@example.net
ftaylor@example.com
bhill@example.org
theresaedwards@example.org
susan65@example.com
kristenlopez@example.com
ubautista@example.net
lucerojoy@example.net
vargaschristopher@example.net
rleonard@example.com
kylejordan@example.net
martincindy@example.org
wyoung@example.net
petersonamanda@example.org
kelleyanne@example.net
anthony89@example.org
rgardner@example.com
erodriguez@example.net
darryl19@example.net
milesroger@example.com
zalexander@example.org
hannah20@example.org
dominguezisaiah@example.net
dawn32@example.com
erodriguez@example.com
robert01@example.org
wrightjames@example.org
dwashington@example.net
michaelbradshaw@example.org
njones@example.com
hkramer@example.org
jackiejohnson@example.com
flee@example.com
jeanmcmahon@example.net
cynthiahamilton@example.net
michelle48@example.com
zsanders@example.com
goodwinanne@example.net
allenconner@example.net
loriweber@example.org
johnsonmichael@example.net
jesseterry@example.net
amyrowland@example.com
stephenayala@example.com
selenalee@example.org
hendersonjennifer@example.net
jasoncrane@example.org
palmeredwin@example.net
kurt03@example.com
solisjonathan@example.net
patriciawright@example.net
rebeccahawkins@example.com
dcopeland@example.net
pburton@example.com
kimberlycastro@example.org
robertsonsharon@example.com
michaelhill@example.com
marthavillegas@example.com
krausechristine@example.net
hensleyclinton@example.org
vmata@example.net
milleryvette@example.net
kimberly62@example.com
laceycisneros@example.org
jaredcooper@example.org
wvargas@example.net
gibsonjohn@example.com
thompsonjill@example.net
sarahsparks@example.com
kpatton@example.com
charles80@example.org
brandonkelly@example.com
leeyolanda@example.org
hwilliams@example.com
nmorgan@example.com
copelandisabella@example.net
hughesbrittany@example.org
hammondalyssa@example.net
yromero@example.org
hayesbrenda@example.net
wendyjimenez@example.net
zstewart@example.com
johnsonsara@example.net
ewingchristopher@example.net
ashleylopez@example.com
jeffrey91@example.net
beckerchristopher@example.org
ecooper@example.com
kimberlyrichardson@example.net
jamesfox@example.net
pallen@example.net
kylesmith@example.net
katherinebailey@example.org
lisa86@example.net
davisjesus@example.com
landryallen@example.org
ismith@example.org
juliewilson@example.net
cmartinez@example.org
linda31@example.com
qvargas@example.net
karen96@example.org
andersonamy@example.org
kennethyates@example.com
karen17@example.org
herringtaylor@example.com
colesteven@example.org
alexhampton@example.net
zfuller@example.net
cmontgomery@example.net
katherineherrera@example.com
juarezjason@example.com
natasha23@example.org
daniel19@example.net
wendy02@example.org
toddwatkins@example.org
yescobar@example.com
williamsosa@example.org
gray@example.net
david71@example.net
bellclaudia@example.net
mandycochran@example.org
jennifermason@example.org
joshuabailey@example.com
brookstheresa@example.com
jennifer03@example.com
sstewart@example.org
dominguezkeith@example.org
kendra75@example.net
michael96@example.com
kreynolds@example.com
lriley@example.org
garciavirginia@example.org
harold98@example.com
nduncan@example.net
jennifer09@example.org
imartin@example.com
jeanherring@example.org
zachary99@example.net
sdunn@example.org
vaughntara@example.org
scottrichards@example.com
clifford53@example.com
qwhite@example.com

In [113]:
def F_df_info(df):
    dat_info=pd.DataFrame({
    'column_name':df.columns.to_list(),
    'data_type':df.dtypes.to_list(),
    'null_count':df.isnull().sum().to_list(),
    'unique_count':df.nunique().to_list(),
    'total_count':[len(df[x]) for x in df.columns]})
    return dat_info

In [114]:
F_df_info(input_df)

     column_name data_type  null_count  unique_count  total_count
0     Unnamed: 0     int64           0          1000         1000
1           Name    object           0           989         1000
2          Email    object           0           996         1000
3            SSN    object           0          1000         1000
4   Phone Number    object           0          1000         1000
5  Date of Birth    object           0           960         1000
6         Income   float64           0          1000         1000

In [116]:
F_df_info(out_data)

     column_name data_type  null_count  unique_count  total_count
0     Unnamed: 0     int64           0          1000         1000
1           Name    object           0           989         1000
2            SSN    object           0          1000         1000
3   Phone Number    object           0          1000         1000
4  Date of Birth    object           0           960         1000
5         Income   float64           0          1000         1000
6          Email    object           0          1000         1000

In [111]:
dat_info=pd.DataFrame({
    'column_name':out_data.columns.to_list(),
    'data_type':out_data.dtypes.to_list(),
    'null_count':out_data.isnull().sum().to_list(),
    'unique_count':out_data.nunique().to_list(),
    'total_count':[len(out_data[x]) for x in out_data.columns]
})

In [161]:
!pip install rsa

Collecting rsa
  Downloading rsa-4.9-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: pyasn1>=0.1.3 in /opt/anaconda3/lib/python3.11/site-packages (from rsa) (0.4.8)
Downloading rsa-4.9-py3-none-any.whl (34 kB)
Installing collected packages: rsa
Successfully installed rsa-4.9

In [160]:
import rsa

ModuleNotFoundError: No module named 'rsa'